name: deployment
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
      - pre
jobs:
  my_first_job:
    name: My first job
    runs-on: [ubuntu-latest]
    steps:
      - run: echo Hello world!
  my_second_job:
    name: My second job
    needs: [my_first_job]
    runs-on: [ubuntu-latest]
    steps:
      - run: echo Second Hello world!
